services:
  postgresdb:
    container_name: retail_orders_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_HOST=${DB_DOCKER_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresdb_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - postgresdb_data:/var/lib/postgresql/data

volumes:
  postgresdb_data:
